create table Person(
                       id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       full_name varchar(255) UNIQUE ,
                       birth_year int CHECK ( birth_year > 1900 AND Person.birth_year < 2025)
);

create table Book(
                     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY ,
                     person_id int REFERENCES person(id) ON DELETE SET NULL ,
                     name varchar(255),
                     author varchar(255),
                     year int CHECK ( year > 0 AND year < 2025)
    );
